<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [6]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists

# Program 1

def matrix_mul(A, B):
    
    R = []
    
    # For A
    no_row_A = len(A)
    no_col_A = len(A[0])

    # For B
    no_row_B = len(B)
    no_col_B = len(B[0])

    if no_col_A == no_row_B:# For A*B
        for i in range(no_row_A):
            l1 = []
            for j in range(no_col_B):
                p = 0
                for k in range(no_row_B):
                    p = p + A[i][k] * B[k][j]
                l1.append(p)
            R.append(l1)
        return(R)
    else:
        print("Since no of columns of first matrix is not equal to the no of rows of second matrix,therefore multiplication is not possible")
        return 0       
    
A = [[1,5],
     [5,3],
     [0,2]]

B = [[1,2,3],
     [5,3,1]]

r = matrix_mul(A, B)
print(r)

[[26, 17, 8], [20, 19, 18], [10, 6, 2]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [1]:
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    bucket = []
    for i in A:
        bucket.extend([i] * i)
    bucket.sort()
    selected_random_number = random.choice(bucket)
    return selected_random_number

def sampling_based_on_magnitued():
    # list enetred by user :https://www.geeksforgeeks.org/python-get-a-list-as-input-from-user/
    A = []
    n = int(input("Enter number of elements:"))
    for i in range(0,n):
        ele = int(input())
        A.append(ele)
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
        print('='*50)
        
sampling_based_on_magnitued()

Enter number of elements:5
2
3
1
5
9
9
9
2
9
9
9
9
9
3
9
5
5
5
5
9
9
2
5
9
3
2
3
2
9
9
9
5
5
9
3
2
9
9
3
9
9
9
5
9
5
9
9
9
3
9
3
9
3
9
9
9
9
3
5
9
3
3
3
5
9
9
2
3
9
9
9
3
2
9
5
9
9
5
9
9
9
9
9
9
3
3
9
5
5
9
5
2
3
5
1
5
3
9
2
1
9
3
1
5


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [7]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # remove spacial character: https://stackoverflow.com/a/5843547/4084039
    # removing special characters
    s = re.sub('[^A-Za-z0-9]+', ' ', String) 

    # how to remove multiple characters from string in python : https://www.journaldev.com/23674/python-remove-character-from-string
    # removing characters from the string 
    s = s.translate({ord(i): None for i in 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'})

    # replacing digits with '#'
    s = s.translate({ord(i): '#' for i in '0123456789'})
    
    # replacing blank spaces with empty string
    final_s = s.replace(" ","")
    return(final_s) # modified string which is after replacing the # with digits

String = str(input("Enter a string:"))
S = replace_digits(String)
print("modified string = ",S)


Enter a string:"jdKI&*kd58j
modified string =  ##


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
import numpy as np # importing numpy just for using arange() function
import math
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    # mapping of two lists :https://www.w3resource.com/python-exercises/dictionary/python-data-type-dictionary-exercise-13.php
    keys = students
    values = marks
    dictionary = dict(zip(keys, values))
    # sorting of dictionary :https://www.saltycrane.com/blog/2007/09/how-to-sort-python-dictionary-by-keys/
    top_5_students = sorted(dictionary.items(), key=lambda item: item[1],reverse = True)[:5] # storing only first five values

    # write code for computing top least 5 students
    least_5_students = sorted(dictionary.items(), key=lambda item: item[1])[:5]
    
    # write code for computing top least 5 students
    marks.sort()
    l = [25,75]
    lst = []
    for i in l:
        p1 = (i/100) * (len(marks))
        inNumberint = int(p1)
        if p1 == inNumberint:
            p = int(p1)
            per = marks[p-1]
            lst.append(per)
        else:
            k1 = math.floor(p1)
            k2 = math.ceil(p1)
            per = (marks[k1-1] + marks[k2-1])/2
            lst.append(per)
    lst1 = []
    for i in dictionary.values():
        if i in np.arange(lst[0],lst[1]+1,0.5):
            lst1.append(i)
    # lst1 contains marks that lies between 25 and 75 percentile 

    m1 = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80] # Taking original list of marks not sorted
    keys = m1
    values = students
    rev_dictionary = dict(zip(keys, values)) # creating new dictionary with marks as keys and students as values
    
    #https://stackoverflow.com/questions/44434575/select-the-keyvalue-pairs-from-a-dictionary-in-python
    students_within_25_and_75 =  {x: rev_dictionary[x] for x in lst1} 

            
    return top_5_students, least_5_students, students_within_25_and_75

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print("top_5_students:",top_5_students)
print("least_5_students",least_5_students)
print("students_within_25_and_75:",students_within_25_and_75)

top_5_students: [('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
least_5_students [('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
students_within_25_and_75: {45: 'student1', 48: 'student5', 43: 'student6', 47: 'student7', 35: 'student9'}


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [9]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    p1 = list(P)

    lst_d = []
    for i in S: 
        lst = []
        lst = list(i)
        q1 = lst[0]*p1[0] + lst[1]*p1[1]
        q2 = math.sqrt((lst[0] * lst[0]) + lst[1] * lst[1])
        q3 = math.sqrt((p1[0] * p1[0]) + p1[1] * p1[1])
        cos_d = math.acos(q1/(q2*q3))
        lst_d.append(cos_d)
    keys = S
    values = lst_d
    dictionary = dict(zip(keys, values))
    l = sorted(dictionary.items(), key=lambda item: item[1])[:5]
    closest_points_to_p1 = []
    for i in l:
        g = list(i)
        closest_points_to_p1.append(g[0])
    return closest_points_to_p1  

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = []
points = closest_points_to_p(S, P)
print(points)

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [10]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def get_coefficients(line):
    import re
    # extract coefficients with floating number :https://stackoverflow.com/questions/4703390/how-to-extract-a-floating-number-from-a-string
    numeric_const_pattern = '[-+]? (?: (?: \d* \. \d+ ) | (?: \d+ \.? ) )(?: [Ee] [+-]? \d+ ) ?'
    rx = re.compile(numeric_const_pattern, re.VERBOSE)
    l = rx.findall(line)
    l = list(map(float, l))
    return l
    
def i_am_the_one(red,blue,line):
    
    line = get_coefficients(line)
    
    lst1 = []
    for j in red:
        l = []
        l = list(j)
        s1 = 0
        s1 = (line[0]*l[0]) + (line[1]*l[1]) + line[2]
        lst1.append(s1)

    lst2 = []
    for j in blue:
        l = []
        l = list(j)
        s2 = 0
        s2 = (line[0]*l[0]) + (line[1]*l[1]) + line[2]
        lst2.append(s2)

    for j in range(len(lst1)):
        if lst1[j] > 0 and lst2[j]<0:
            return 'Yes'
        else:
            return 'NO'

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    g= i_am_the_one(Red, Blue,i)
    print(g) 

Yes
NO
NO
Yes


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [11]:
def fun1(i,lst1):
    if (i+1) == len(lst1):
        k = int(lst1[i])
        for j in range(len(lst1)):
            lst1[j] = k/(i+1)
        return lst1
    elif (i+1) != len(lst1):
        k = int(lst1[i])
        for j in range(0,i+1):
            lst1[j] = k/(i+1)
        lst1 = fun2(lst1,i+1)
        return lst1
def fun2(lst1,b):
    c1 = b
    c2 = 0
    while lst1[c1] == '_':
        c2 += 1
        c1 += 1
    c3 = c1 + 1
    c2 = c2 + 2
    if c3 == len(lst1):
        for k in range(b-1,len(lst1)):
            lst1[k] = (int(lst1[b-1]) + int(lst1[c1]))/c2
        return lst1
    else:
        k1 = int(lst1[b-1])
        k2 = int(lst1[c1])
        for k in range(b-1,c3):
            lst1[k] = (k1+k2)/c2
        c = 0
        for k in range(c3,len(lst1)):
            c += 1
        c = c + 1
        c4 = c3 - 1
        k1 = int(lst1[c4])
        for j in range(c4,len(lst1)):
            lst1[j] = k1/c
        return lst1
def fun3(lst1):
    c1 = 1
    c2 = 0
    while (c1+1) != len(lst1):
            c1 += 1
            c2 += 1
    c2 = c2 + 2
    if lst1[len(lst1)-1] == '_':
        k1 = int(lst1[0])
        for j in range(0,len(lst1)):
            lst1[j] = k1/c2
        return lst1 
    elif lst1[c1] != '_':
        
    
        k1 = int(lst1[0])
        k2 = int(lst1[c1])
        for j in range(0,len(lst1)):
            lst1[j] = (k1+k2)/c2
        return lst1       

In [12]:
S=  "_,_,30,_,_,_,50,_,_"
#len(S)
lst1 = S.split(',')
print(lst1)
if lst1[0] != '_':
    lst1  = fun3(lst1)
    print(lst1)
elif lst1[0] == '_':
    for i in range(len(lst1)):
        if lst1[i] != '_':
            break
    lst1 = fun1(i,lst1)
    print(lst1)

['_', '_', '30', '_', '_', '_', '50', '_', '_']
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [13]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    l1 = [0] * 3
    l2 = [0] * 3
    S = ['S1','S2','S3']
    for i in A:
        if i[1] == 'S1':
            l2[0] += 1
        if i[1] == 'S2':
            l2[1] += 1
        if i[1] == 'S3':
            l2[2] += 1
        if i[0] == 'F1' and i[1] == 'S1':
            l1[0] += 1
        if i[0] == 'F1' and i[1] == 'S2':
            l1[1] += 1
        if i[0] == 'F1' and i[1] == 'S3':
            l1[2] += 1
    
    for i in range(len(l1)):
        print("P(F=F1|S=={0})= {1}/{2}".format(S[i],l1[i],l2[i]))
    print('='*50)
    
    l1 = [0] * 3
    
    for i in A:
        if i[0] == 'F2' and i[1] == 'S1':
            l1[0] += 1
        if i[0] == 'F2' and i[1] == 'S2':
            l1[1] += 1
        if i[0] == 'F2' and i[1] == 'S3':
            l1[2] += 1
    
    for i in range(len(l1)):
        print("P(F=F2|S=={0})= {1}/{2}".format(S[i],l1[i],l2[i]))
    print('='*50)

    l1 = [0] * 3
    
    for i in A:
        if i[0] == 'F3' and i[1] == 'S1':
            l1[0] += 1
        if i[0] == 'F3' and i[1] == 'S2':
            l1[1] += 1
        if i[0] == 'F3' and i[1] == 'S3':
            l1[2] += 1
    
    for i in range(len(l1)):
        print("P(F=F3|S=={0})= {1}/{2}".format(S[i],l1[i],l2[i]))
    print('='*50)
    
    l1 = [0] * 3
    
    for i in A:
        if i[0] == 'F4' and i[1] == 'S1':
            l1[0] += 1
        if i[0] == 'F4' and i[1] == 'S2':
            l1[1] += 1
        if i[0] == 'F4' and i[1] == 'S3':
            l1[2] += 1
    
    for i in range(len(l1)):
        print("P(F=F4|S=={0})= {1}/{2}".format(S[i],l1[i],l2[i]))
    print('='*50)
    
    l1 = [0] * 3
    
    for i in A:
        if i[0] == 'F5' and i[1] == 'S1':
            l1[0] += 1
        if i[0] == 'F5' and i[1] == 'S2':
            l1[1] += 1
        if i[0] == 'F5' and i[1] == 'S3':
            l1[2] += 1

    for i in range(len(l1)):
        print("P(F=F5|S=={0})= {1}/{2}".format(S[i],l1[i],l2[i]))

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1/4
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0/3
P(F=F2|S==S1)= 1/4
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F3|S==S1)= 0/4
P(F=F3|S==S2)= 1/3
P(F=F3|S==S3)= 1/3
P(F=F4|S==S1)= 1/4
P(F=F4|S==S2)= 0/3
P(F=F4|S==S3)= 1/3
P(F=F5|S==S1)= 1/4
P(F=F5|S==S2)= 0/3
P(F=F5|S==S3)= 0/3


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [14]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    lst1 = S1.split()
    lst2 = S2.split()
    l1 = len(lst1)
    l2 = len(lst2)
    count = 0
    
    # loop to calculate number of common words in two strings
    for i in range(l1):
        for j in range(l2):
            if lst1[i] == lst2[j]:
                count += 1
                
    l1 = []
    # loop to find words that exist in S1 but not in S2
    for i in lst1:
        if i not in lst2:
            l1.append(i)
    
    l2 = []
    # loop to find words that exist in S1 but not in S2
    for i in lst2:
        if i not in lst1:
            l2.append(i)
    return count,l1,l2
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
b = []
c = []
a,b,c = string_features(S1, S2)
print("Number of common words = ",a)
print("Words in S1 but not in S2:",b)
print("Words in S2 but not in S1:",c)

Number of common words =  7
Words in S1 but not in S2: ['first', 'F', '5']
Words in S2 but not in S1: ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [16]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math as m
def compute_log_loss(A):
    loss = 0
    for i in A:
        loss = loss + ((-1)*(1/8)*((i[0]*m.log(i[1],10) + (1-i[0])*m.log((1-i[1]),10))))
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
