In [25]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [26]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]
print(data)

              f1            f2        f3    y
0    -195.871045 -14843.084171  5.532140  1.0
1   -1217.183964  -4068.124621  4.416082  1.0
2       9.138451   4413.412028  0.425317  0.0
3     363.824242  15474.760647  1.094119  0.0
4    -768.812047  -7963.932192  1.870536  0.0
5     192.093461 -12677.139687  3.456229  0.0
6    -118.048303 -27479.657522  9.407845  1.0
7     -38.987574   3599.957386  2.999579  0.0
8     -31.315888 -15289.241646  3.882981  0.0
9      55.379493  -9020.326833  7.759002  1.0
10    355.555296 -16420.510738  1.968104  0.0
11   -371.562551  -2334.218517  2.231601  0.0
12    -88.026450  19231.356969  8.423247  1.0
13   -397.206299 -11850.400847  1.728038  0.0
14    111.023077  13041.834444  0.148890  0.0
15    469.423185   5845.404919  5.192703  0.0
16   -165.222463    961.661312  3.298669  0.0
17    141.946802  24131.360720  3.085033  0.0
18   -307.164095  11990.468797  8.656600  1.0
19   -286.559810   9984.332766  6.762725  1.0
20    397.219043  -5682.387579  9.

In [27]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [28]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [29]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [31]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)
Y

(200, 3)
(200,)


array([1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.])

# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

### Task 1:-

#### 1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance

In [38]:
# https://stackoverflow.com/questions/15777951/how-to-suppress-pandas-future-warning
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from sklearn.linear_model import SGDClassifier
model = SGDClassifier(loss = 'log')
model.fit(X,Y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [39]:
model.coef_

array([[31558.52325093, 15221.75557601,  5800.06994567]])

#### OBSERVATION:-

__Since in weight vector weight corresponding to feature 'f1' and feature 'f2' are much higher than feature 'f3'.Therefore features 'f1' and 'f2' are important and least important feature is 'f3'.__

#### 2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

In [40]:
model = SGDClassifier(loss = 'hinge')
model.fit(X,Y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [41]:
model.coef_

array([[ 43983.13717904, -40590.58060102,   5911.81842849]])

#### OBSERVATION:-

__For this model feature 'f1' has more positive value than feature 'f3',therefore 'f1' is more important than feature 'f3'.And value of feature 'f2' is more negative than the positive value of 'f3',hence 'f2' is also a important feature in determining a point as negative class.Therefore importanat features are 'f1' and 'f3'.__

### Task2:-

#### 1.Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
       

In [44]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(X)

In [45]:
from sklearn.linear_model import SGDClassifier
model = SGDClassifier(loss = 'log')
model.fit(scaled_data,Y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [46]:
model.coef_

array([[-9.67720213, -1.59333926, 33.1837174 ]])

#### OBSERVATION:-

__For this model most important feature is 'f3',as it's corresponding weight vector is highest among all the features.If we have to choose 2nd most important feature,then it would be 'f1',as it has highest negative value.__ 

#### 2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
       

In [47]:
from sklearn.linear_model import SGDClassifier
model = SGDClassifier(loss = 'hinge')
model.fit(scaled_data,Y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [48]:
model.coef_

array([[ 6.94622205, 10.0353215 , 37.47962223]])

#### OBSERVATION:-

__Most important features are 'f3' and 'f2',as thier corresponding weight values are higher and hence will correspond more in identifying a query point as positive or negative.__ 